/* Ex.1-20
 * Write a program detab that replaces tabs in the input with the proper 
 * number of blanks to space to the next tab stop. Assume a fixed set of tab 
 * stops, say every n columns. Should n be a variable or a symbolic parameter?
 * -------------------------------------------------------------------------- */

#include <stdio.h>

#define MAXBUFFER 2 /* Buffer Size */
#define TABCOLS   4 /* How long are the tabs? */

/* Unfortunately forced to keep some stuff global, to accomodate
 * for buffers that are smaller than MAXBUFFER. 
 * */

int tabstopcounter = 0; /* Keep track of tabstops */
int spacecounter   = 0; /* Keep track of extra spaces generated by tabs. */

/* Read from standard input into a specified buffer of specified length, while
 * replacing every encountered tab with an appropriate amount of spaces.
 * Assumes tabstops are every TABCOLS characters. 
 * Cannot handle lengths of less than 2.
 * Returns the length of the filled buffer, or an error code.
 * */
int detab(char buffer[], int length) {
    /* Can't have a length less than 2, since we need at least one character
     * for getting something meaningful and 1 character for null terminator. */
    if (length < 2) {
        fprintf(stderr, "Sorry, buffers of length<2 are not supported.");
        return -1;
    }

    int i, c;
    i = 0;

    /* First see if we have some extra space we need to put from the last
     * call to this function. This could happen if the buffer faced an overflow.
     * */
    while (i < length-1 && spacecounter > 0) {
        buffer[i] = ' ';
        ++i;
        --spacecounter;
    }

    while (i < length-1 && (c=getchar()) != EOF) {
        if (c == '\t') {
            /* We want to replace this tab by some amount of spaces. 
             * Has to be based on tabstops. So, keep track of the global
             * tabstopcounter, increase it whenever we insert
             * a non-tab character, and set it to 0 every time it reaches 
             * TABCOLS or after we encounter a tab, or if we start a new line.
             * */ 
            spacecounter += TABCOLS-tabstopcounter;
            tabstopcounter = 0;

            /* Insert as many spaces as we need and can. 
             * If some will be left uninserted, we will insert them first
             * thing on the next call to this function.
             * */
            while (i < length-1 && spacecounter > 0) {
                buffer[i] = ' ';
                ++i;
                --spacecounter;
            }
        }
        else {
            /* If we encounter a regular char, just insert it. */
            buffer[i] = c;
            ++i;
            /* Drop the counter if we start a new line or if we hit TABCOLS. */
            if (c == '\n' || ++tabstopcounter >= TABCOLS) {
                tabstopcounter = 0;
            }
        }
    }

    /* End the string. */
    buffer[i] = '\0';

    return i;
}

int main() {
    char buffer[MAXBUFFER];

    while(detab(buffer, MAXBUFFER) > 0) {
        printf("%s", buffer);
    }
    
    return 0;
}
